---
- name: package
  hosts: '{{ system }}'
  become: yes
  vars_files:
   - /opt/mdb.yml
  tasks:
   - name: "APT: Install aptitude package"
     apt:
      name: aptitude
      force_apt_get: yes
   - name: python-apt file
     apt:
      name: python-apt
      state: latest
