---
- name: Postman install
  hosts: '{{ system }}'
  become: yes
  vars_files:
   - /opt/mdb.yml
  tasks:
   - name: Unarchive tar file
     unarchive:
      src: '{{ postman }}'
      dest: /opt/
   - name: Permission for postman folder
     file:
      path: /opt/Postman
      owner: '{{ user }}'
      group: '{{ user }}'
      mode: '0755'
      state: directory
      recurse: yes
   - name: Create symbolic link 
     file: 
      src: "/opt/Postman/Postman"
      dest: "/usr/bin/postman"
      state: link
      owner: '{{ user }}'
      group: '{{ user }}'
   

